#SVD Shape Recognizer settings
#Sat Sep 26 19:21:34 MSK 2026
recognition.mode=SUBSPACE
subspace.threshold=15.0
threshold.CIRCLE=0.38863682487233
threshold.RECTANGLE=0.5884396510783803
threshold.TRIANGLE=0.2792174008142783
faces.dataset.dir=D\:\\data\\ORL
faces.models.dir=D\:\\data\\models\\opencv_zoo
faces.gt.dir=D\:\\data\\GeorgiaTech\\gt_db
faces.muct.dir=D\:\\data\\MUCT\\jpg
faces.own.dir=D\:\\data\\SpiiranDataSet
